import { GithubUser } from "../../types";

export const initialUser: GithubUser = {
  login: "jadolg",
  id: 5427672,
  node_id: "MDQ6VXNlcjU0Mjc2NzI=",
  avatar_url: "https://avatars.githubusercontent.com/u/5427672?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/jadolg",
  html_url: "https://github.com/jadolg",
  followers_url: "https://api.github.com/users/jadolg/followers",
  following_url: "https://api.github.com/users/jadolg/following{/other_user}",
  gists_url: "https://api.github.com/users/jadolg/gists{/gist_id}",
  starred_url: "https://api.github.com/users/jadolg/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/jadolg/subscriptions",
  organizations_url: "https://api.github.com/users/jadolg/orgs",
  repos_url: "https://api.github.com/users/jadolg/repos",
  events_url: "https://api.github.com/users/jadolg/events{/privacy}",
  received_events_url: "https://api.github.com/users/jadolg/received_events",
  type: "User",
  site_admin: false,
  name: "Jorge Alberto Díaz Orozco (Akiel)",
  company: null,
  blog: "https://dev.to/jadolg",
  location: "Hamburg, Germany",
  email: null,
  hireable: null,
  bio: "Pythonista and GO enthusiast. I write Open Source for fun.",
  twitter_username: "jadolg91",
  public_repos: 72,
  public_gists: 7,
  followers: 90,
  following: 119,
  created_at: "2013-09-10T13:54:06Z",
  updated_at: "2022-03-03T16:50:49Z",
};
