import { BasicGithubUser } from "../../types";

export const initialFollowers: BasicGithubUser[] = [
  {
    login: "aNeutrino",
    id: 38576,
    node_id: "MDQ6VXNlcjM4NTc2",
    avatar_url: "https://avatars.githubusercontent.com/u/38576?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/aNeutrino",
    html_url: "https://github.com/aNeutrino",
    followers_url: "https://api.github.com/users/aNeutrino/followers",
    following_url:
      "https://api.github.com/users/aNeutrino/following{/other_user}",
    gists_url: "https://api.github.com/users/aNeutrino/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/aNeutrino/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/aNeutrino/subscriptions",
    organizations_url: "https://api.github.com/users/aNeutrino/orgs",
    repos_url: "https://api.github.com/users/aNeutrino/repos",
    events_url: "https://api.github.com/users/aNeutrino/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/aNeutrino/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "BuZZ-dEE",
    id: 125954,
    node_id: "MDQ6VXNlcjEyNTk1NA==",
    avatar_url: "https://avatars.githubusercontent.com/u/125954?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/BuZZ-dEE",
    html_url: "https://github.com/BuZZ-dEE",
    followers_url: "https://api.github.com/users/BuZZ-dEE/followers",
    following_url:
      "https://api.github.com/users/BuZZ-dEE/following{/other_user}",
    gists_url: "https://api.github.com/users/BuZZ-dEE/gists{/gist_id}",
    starred_url: "https://api.github.com/users/BuZZ-dEE/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/BuZZ-dEE/subscriptions",
    organizations_url: "https://api.github.com/users/BuZZ-dEE/orgs",
    repos_url: "https://api.github.com/users/BuZZ-dEE/repos",
    events_url: "https://api.github.com/users/BuZZ-dEE/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/BuZZ-dEE/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "muelli",
    id: 322807,
    node_id: "MDQ6VXNlcjMyMjgwNw==",
    avatar_url: "https://avatars.githubusercontent.com/u/322807?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/muelli",
    html_url: "https://github.com/muelli",
    followers_url: "https://api.github.com/users/muelli/followers",
    following_url: "https://api.github.com/users/muelli/following{/other_user}",
    gists_url: "https://api.github.com/users/muelli/gists{/gist_id}",
    starred_url: "https://api.github.com/users/muelli/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/muelli/subscriptions",
    organizations_url: "https://api.github.com/users/muelli/orgs",
    repos_url: "https://api.github.com/users/muelli/repos",
    events_url: "https://api.github.com/users/muelli/events{/privacy}",
    received_events_url: "https://api.github.com/users/muelli/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "localjo",
    id: 516388,
    node_id: "MDQ6VXNlcjUxNjM4OA==",
    avatar_url: "https://avatars.githubusercontent.com/u/516388?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/localjo",
    html_url: "https://github.com/localjo",
    followers_url: "https://api.github.com/users/localjo/followers",
    following_url:
      "https://api.github.com/users/localjo/following{/other_user}",
    gists_url: "https://api.github.com/users/localjo/gists{/gist_id}",
    starred_url: "https://api.github.com/users/localjo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/localjo/subscriptions",
    organizations_url: "https://api.github.com/users/localjo/orgs",
    repos_url: "https://api.github.com/users/localjo/repos",
    events_url: "https://api.github.com/users/localjo/events{/privacy}",
    received_events_url: "https://api.github.com/users/localjo/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "yeysus",
    id: 913259,
    node_id: "MDQ6VXNlcjkxMzI1OQ==",
    avatar_url: "https://avatars.githubusercontent.com/u/913259?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/yeysus",
    html_url: "https://github.com/yeysus",
    followers_url: "https://api.github.com/users/yeysus/followers",
    following_url: "https://api.github.com/users/yeysus/following{/other_user}",
    gists_url: "https://api.github.com/users/yeysus/gists{/gist_id}",
    starred_url: "https://api.github.com/users/yeysus/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/yeysus/subscriptions",
    organizations_url: "https://api.github.com/users/yeysus/orgs",
    repos_url: "https://api.github.com/users/yeysus/repos",
    events_url: "https://api.github.com/users/yeysus/events{/privacy}",
    received_events_url: "https://api.github.com/users/yeysus/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "rogertm",
    id: 1044820,
    node_id: "MDQ6VXNlcjEwNDQ4MjA=",
    avatar_url: "https://avatars.githubusercontent.com/u/1044820?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rogertm",
    html_url: "https://github.com/rogertm",
    followers_url: "https://api.github.com/users/rogertm/followers",
    following_url:
      "https://api.github.com/users/rogertm/following{/other_user}",
    gists_url: "https://api.github.com/users/rogertm/gists{/gist_id}",
    starred_url: "https://api.github.com/users/rogertm/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rogertm/subscriptions",
    organizations_url: "https://api.github.com/users/rogertm/orgs",
    repos_url: "https://api.github.com/users/rogertm/repos",
    events_url: "https://api.github.com/users/rogertm/events{/privacy}",
    received_events_url: "https://api.github.com/users/rogertm/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "azubieta",
    id: 1138094,
    node_id: "MDQ6VXNlcjExMzgwOTQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/1138094?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/azubieta",
    html_url: "https://github.com/azubieta",
    followers_url: "https://api.github.com/users/azubieta/followers",
    following_url:
      "https://api.github.com/users/azubieta/following{/other_user}",
    gists_url: "https://api.github.com/users/azubieta/gists{/gist_id}",
    starred_url: "https://api.github.com/users/azubieta/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/azubieta/subscriptions",
    organizations_url: "https://api.github.com/users/azubieta/orgs",
    repos_url: "https://api.github.com/users/azubieta/repos",
    events_url: "https://api.github.com/users/azubieta/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/azubieta/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dlnan",
    id: 1246043,
    node_id: "MDQ6VXNlcjEyNDYwNDM=",
    avatar_url: "https://avatars.githubusercontent.com/u/1246043?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dlnan",
    html_url: "https://github.com/dlnan",
    followers_url: "https://api.github.com/users/dlnan/followers",
    following_url: "https://api.github.com/users/dlnan/following{/other_user}",
    gists_url: "https://api.github.com/users/dlnan/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dlnan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dlnan/subscriptions",
    organizations_url: "https://api.github.com/users/dlnan/orgs",
    repos_url: "https://api.github.com/users/dlnan/repos",
    events_url: "https://api.github.com/users/dlnan/events{/privacy}",
    received_events_url: "https://api.github.com/users/dlnan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dxas90",
    id: 1261887,
    node_id: "MDQ6VXNlcjEyNjE4ODc=",
    avatar_url: "https://avatars.githubusercontent.com/u/1261887?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dxas90",
    html_url: "https://github.com/dxas90",
    followers_url: "https://api.github.com/users/dxas90/followers",
    following_url: "https://api.github.com/users/dxas90/following{/other_user}",
    gists_url: "https://api.github.com/users/dxas90/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dxas90/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dxas90/subscriptions",
    organizations_url: "https://api.github.com/users/dxas90/orgs",
    repos_url: "https://api.github.com/users/dxas90/repos",
    events_url: "https://api.github.com/users/dxas90/events{/privacy}",
    received_events_url: "https://api.github.com/users/dxas90/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "xexuy",
    id: 1274057,
    node_id: "MDQ6VXNlcjEyNzQwNTc=",
    avatar_url: "https://avatars.githubusercontent.com/u/1274057?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/xexuy",
    html_url: "https://github.com/xexuy",
    followers_url: "https://api.github.com/users/xexuy/followers",
    following_url: "https://api.github.com/users/xexuy/following{/other_user}",
    gists_url: "https://api.github.com/users/xexuy/gists{/gist_id}",
    starred_url: "https://api.github.com/users/xexuy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/xexuy/subscriptions",
    organizations_url: "https://api.github.com/users/xexuy/orgs",
    repos_url: "https://api.github.com/users/xexuy/repos",
    events_url: "https://api.github.com/users/xexuy/events{/privacy}",
    received_events_url: "https://api.github.com/users/xexuy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "xr09",
    id: 1380243,
    node_id: "MDQ6VXNlcjEzODAyNDM=",
    avatar_url: "https://avatars.githubusercontent.com/u/1380243?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/xr09",
    html_url: "https://github.com/xr09",
    followers_url: "https://api.github.com/users/xr09/followers",
    following_url: "https://api.github.com/users/xr09/following{/other_user}",
    gists_url: "https://api.github.com/users/xr09/gists{/gist_id}",
    starred_url: "https://api.github.com/users/xr09/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/xr09/subscriptions",
    organizations_url: "https://api.github.com/users/xr09/orgs",
    repos_url: "https://api.github.com/users/xr09/repos",
    events_url: "https://api.github.com/users/xr09/events{/privacy}",
    received_events_url: "https://api.github.com/users/xr09/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dasouch",
    id: 1742818,
    node_id: "MDQ6VXNlcjE3NDI4MTg=",
    avatar_url: "https://avatars.githubusercontent.com/u/1742818?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dasouch",
    html_url: "https://github.com/dasouch",
    followers_url: "https://api.github.com/users/dasouch/followers",
    following_url:
      "https://api.github.com/users/dasouch/following{/other_user}",
    gists_url: "https://api.github.com/users/dasouch/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dasouch/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dasouch/subscriptions",
    organizations_url: "https://api.github.com/users/dasouch/orgs",
    repos_url: "https://api.github.com/users/dasouch/repos",
    events_url: "https://api.github.com/users/dasouch/events{/privacy}",
    received_events_url: "https://api.github.com/users/dasouch/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Wilo",
    id: 1874853,
    node_id: "MDQ6VXNlcjE4NzQ4NTM=",
    avatar_url: "https://avatars.githubusercontent.com/u/1874853?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Wilo",
    html_url: "https://github.com/Wilo",
    followers_url: "https://api.github.com/users/Wilo/followers",
    following_url: "https://api.github.com/users/Wilo/following{/other_user}",
    gists_url: "https://api.github.com/users/Wilo/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Wilo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Wilo/subscriptions",
    organizations_url: "https://api.github.com/users/Wilo/orgs",
    repos_url: "https://api.github.com/users/Wilo/repos",
    events_url: "https://api.github.com/users/Wilo/events{/privacy}",
    received_events_url: "https://api.github.com/users/Wilo/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "pgpbpadilla",
    id: 1960829,
    node_id: "MDQ6VXNlcjE5NjA4Mjk=",
    avatar_url: "https://avatars.githubusercontent.com/u/1960829?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/pgpbpadilla",
    html_url: "https://github.com/pgpbpadilla",
    followers_url: "https://api.github.com/users/pgpbpadilla/followers",
    following_url:
      "https://api.github.com/users/pgpbpadilla/following{/other_user}",
    gists_url: "https://api.github.com/users/pgpbpadilla/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/pgpbpadilla/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/pgpbpadilla/subscriptions",
    organizations_url: "https://api.github.com/users/pgpbpadilla/orgs",
    repos_url: "https://api.github.com/users/pgpbpadilla/repos",
    events_url: "https://api.github.com/users/pgpbpadilla/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/pgpbpadilla/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dogcalas",
    id: 2521769,
    node_id: "MDQ6VXNlcjI1MjE3Njk=",
    avatar_url: "https://avatars.githubusercontent.com/u/2521769?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dogcalas",
    html_url: "https://github.com/dogcalas",
    followers_url: "https://api.github.com/users/dogcalas/followers",
    following_url:
      "https://api.github.com/users/dogcalas/following{/other_user}",
    gists_url: "https://api.github.com/users/dogcalas/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dogcalas/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dogcalas/subscriptions",
    organizations_url: "https://api.github.com/users/dogcalas/orgs",
    repos_url: "https://api.github.com/users/dogcalas/repos",
    events_url: "https://api.github.com/users/dogcalas/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/dogcalas/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jayhack",
    id: 2548876,
    node_id: "MDQ6VXNlcjI1NDg4NzY=",
    avatar_url: "https://avatars.githubusercontent.com/u/2548876?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jayhack",
    html_url: "https://github.com/jayhack",
    followers_url: "https://api.github.com/users/jayhack/followers",
    following_url:
      "https://api.github.com/users/jayhack/following{/other_user}",
    gists_url: "https://api.github.com/users/jayhack/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jayhack/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jayhack/subscriptions",
    organizations_url: "https://api.github.com/users/jayhack/orgs",
    repos_url: "https://api.github.com/users/jayhack/repos",
    events_url: "https://api.github.com/users/jayhack/events{/privacy}",
    received_events_url: "https://api.github.com/users/jayhack/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "soyelmnd",
    id: 2678063,
    node_id: "MDQ6VXNlcjI2NzgwNjM=",
    avatar_url: "https://avatars.githubusercontent.com/u/2678063?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/soyelmnd",
    html_url: "https://github.com/soyelmnd",
    followers_url: "https://api.github.com/users/soyelmnd/followers",
    following_url:
      "https://api.github.com/users/soyelmnd/following{/other_user}",
    gists_url: "https://api.github.com/users/soyelmnd/gists{/gist_id}",
    starred_url: "https://api.github.com/users/soyelmnd/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/soyelmnd/subscriptions",
    organizations_url: "https://api.github.com/users/soyelmnd/orgs",
    repos_url: "https://api.github.com/users/soyelmnd/repos",
    events_url: "https://api.github.com/users/soyelmnd/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/soyelmnd/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "rlclaro",
    id: 3267491,
    node_id: "MDQ6VXNlcjMyNjc0OTE=",
    avatar_url: "https://avatars.githubusercontent.com/u/3267491?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rlclaro",
    html_url: "https://github.com/rlclaro",
    followers_url: "https://api.github.com/users/rlclaro/followers",
    following_url:
      "https://api.github.com/users/rlclaro/following{/other_user}",
    gists_url: "https://api.github.com/users/rlclaro/gists{/gist_id}",
    starred_url: "https://api.github.com/users/rlclaro/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rlclaro/subscriptions",
    organizations_url: "https://api.github.com/users/rlclaro/orgs",
    repos_url: "https://api.github.com/users/rlclaro/repos",
    events_url: "https://api.github.com/users/rlclaro/events{/privacy}",
    received_events_url: "https://api.github.com/users/rlclaro/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nilsandrey",
    id: 3579285,
    node_id: "MDQ6VXNlcjM1NzkyODU=",
    avatar_url: "https://avatars.githubusercontent.com/u/3579285?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nilsandrey",
    html_url: "https://github.com/nilsandrey",
    followers_url: "https://api.github.com/users/nilsandrey/followers",
    following_url:
      "https://api.github.com/users/nilsandrey/following{/other_user}",
    gists_url: "https://api.github.com/users/nilsandrey/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/nilsandrey/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nilsandrey/subscriptions",
    organizations_url: "https://api.github.com/users/nilsandrey/orgs",
    repos_url: "https://api.github.com/users/nilsandrey/repos",
    events_url: "https://api.github.com/users/nilsandrey/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/nilsandrey/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "laith-leo",
    id: 4406186,
    node_id: "MDQ6VXNlcjQ0MDYxODY=",
    avatar_url: "https://avatars.githubusercontent.com/u/4406186?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/laith-leo",
    html_url: "https://github.com/laith-leo",
    followers_url: "https://api.github.com/users/laith-leo/followers",
    following_url:
      "https://api.github.com/users/laith-leo/following{/other_user}",
    gists_url: "https://api.github.com/users/laith-leo/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/laith-leo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/laith-leo/subscriptions",
    organizations_url: "https://api.github.com/users/laith-leo/orgs",
    repos_url: "https://api.github.com/users/laith-leo/repos",
    events_url: "https://api.github.com/users/laith-leo/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/laith-leo/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ikario404",
    id: 4442790,
    node_id: "MDQ6VXNlcjQ0NDI3OTA=",
    avatar_url: "https://avatars.githubusercontent.com/u/4442790?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ikario404",
    html_url: "https://github.com/ikario404",
    followers_url: "https://api.github.com/users/ikario404/followers",
    following_url:
      "https://api.github.com/users/ikario404/following{/other_user}",
    gists_url: "https://api.github.com/users/ikario404/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ikario404/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ikario404/subscriptions",
    organizations_url: "https://api.github.com/users/ikario404/orgs",
    repos_url: "https://api.github.com/users/ikario404/repos",
    events_url: "https://api.github.com/users/ikario404/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ikario404/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "aleguerra05",
    id: 5543818,
    node_id: "MDQ6VXNlcjU1NDM4MTg=",
    avatar_url: "https://avatars.githubusercontent.com/u/5543818?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/aleguerra05",
    html_url: "https://github.com/aleguerra05",
    followers_url: "https://api.github.com/users/aleguerra05/followers",
    following_url:
      "https://api.github.com/users/aleguerra05/following{/other_user}",
    gists_url: "https://api.github.com/users/aleguerra05/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/aleguerra05/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/aleguerra05/subscriptions",
    organizations_url: "https://api.github.com/users/aleguerra05/orgs",
    repos_url: "https://api.github.com/users/aleguerra05/repos",
    events_url: "https://api.github.com/users/aleguerra05/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/aleguerra05/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "navs91",
    id: 5817901,
    node_id: "MDQ6VXNlcjU4MTc5MDE=",
    avatar_url: "https://avatars.githubusercontent.com/u/5817901?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/navs91",
    html_url: "https://github.com/navs91",
    followers_url: "https://api.github.com/users/navs91/followers",
    following_url: "https://api.github.com/users/navs91/following{/other_user}",
    gists_url: "https://api.github.com/users/navs91/gists{/gist_id}",
    starred_url: "https://api.github.com/users/navs91/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/navs91/subscriptions",
    organizations_url: "https://api.github.com/users/navs91/orgs",
    repos_url: "https://api.github.com/users/navs91/repos",
    events_url: "https://api.github.com/users/navs91/events{/privacy}",
    received_events_url: "https://api.github.com/users/navs91/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "codeshard",
    id: 5880754,
    node_id: "MDQ6VXNlcjU4ODA3NTQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/5880754?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/codeshard",
    html_url: "https://github.com/codeshard",
    followers_url: "https://api.github.com/users/codeshard/followers",
    following_url:
      "https://api.github.com/users/codeshard/following{/other_user}",
    gists_url: "https://api.github.com/users/codeshard/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/codeshard/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/codeshard/subscriptions",
    organizations_url: "https://api.github.com/users/codeshard/orgs",
    repos_url: "https://api.github.com/users/codeshard/repos",
    events_url: "https://api.github.com/users/codeshard/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/codeshard/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jcurbelo",
    id: 5923174,
    node_id: "MDQ6VXNlcjU5MjMxNzQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/5923174?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jcurbelo",
    html_url: "https://github.com/jcurbelo",
    followers_url: "https://api.github.com/users/jcurbelo/followers",
    following_url:
      "https://api.github.com/users/jcurbelo/following{/other_user}",
    gists_url: "https://api.github.com/users/jcurbelo/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jcurbelo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jcurbelo/subscriptions",
    organizations_url: "https://api.github.com/users/jcurbelo/orgs",
    repos_url: "https://api.github.com/users/jcurbelo/repos",
    events_url: "https://api.github.com/users/jcurbelo/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jcurbelo/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gvieralopez",
    id: 6260065,
    node_id: "MDQ6VXNlcjYyNjAwNjU=",
    avatar_url: "https://avatars.githubusercontent.com/u/6260065?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gvieralopez",
    html_url: "https://github.com/gvieralopez",
    followers_url: "https://api.github.com/users/gvieralopez/followers",
    following_url:
      "https://api.github.com/users/gvieralopez/following{/other_user}",
    gists_url: "https://api.github.com/users/gvieralopez/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/gvieralopez/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/gvieralopez/subscriptions",
    organizations_url: "https://api.github.com/users/gvieralopez/orgs",
    repos_url: "https://api.github.com/users/gvieralopez/repos",
    events_url: "https://api.github.com/users/gvieralopez/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/gvieralopez/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "edelvalle",
    id: 6555851,
    node_id: "MDQ6VXNlcjY1NTU4NTE=",
    avatar_url: "https://avatars.githubusercontent.com/u/6555851?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/edelvalle",
    html_url: "https://github.com/edelvalle",
    followers_url: "https://api.github.com/users/edelvalle/followers",
    following_url:
      "https://api.github.com/users/edelvalle/following{/other_user}",
    gists_url: "https://api.github.com/users/edelvalle/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/edelvalle/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/edelvalle/subscriptions",
    organizations_url: "https://api.github.com/users/edelvalle/orgs",
    repos_url: "https://api.github.com/users/edelvalle/repos",
    events_url: "https://api.github.com/users/edelvalle/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/edelvalle/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mmcloughlin",
    id: 7133685,
    node_id: "MDQ6VXNlcjcxMzM2ODU=",
    avatar_url: "https://avatars.githubusercontent.com/u/7133685?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mmcloughlin",
    html_url: "https://github.com/mmcloughlin",
    followers_url: "https://api.github.com/users/mmcloughlin/followers",
    following_url:
      "https://api.github.com/users/mmcloughlin/following{/other_user}",
    gists_url: "https://api.github.com/users/mmcloughlin/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mmcloughlin/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mmcloughlin/subscriptions",
    organizations_url: "https://api.github.com/users/mmcloughlin/orgs",
    repos_url: "https://api.github.com/users/mmcloughlin/repos",
    events_url: "https://api.github.com/users/mmcloughlin/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mmcloughlin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hiancdtrsnm",
    id: 7343177,
    node_id: "MDQ6VXNlcjczNDMxNzc=",
    avatar_url: "https://avatars.githubusercontent.com/u/7343177?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hiancdtrsnm",
    html_url: "https://github.com/hiancdtrsnm",
    followers_url: "https://api.github.com/users/hiancdtrsnm/followers",
    following_url:
      "https://api.github.com/users/hiancdtrsnm/following{/other_user}",
    gists_url: "https://api.github.com/users/hiancdtrsnm/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hiancdtrsnm/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hiancdtrsnm/subscriptions",
    organizations_url: "https://api.github.com/users/hiancdtrsnm/orgs",
    repos_url: "https://api.github.com/users/hiancdtrsnm/repos",
    events_url: "https://api.github.com/users/hiancdtrsnm/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hiancdtrsnm/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "alxrcs",
    id: 8171561,
    node_id: "MDQ6VXNlcjgxNzE1NjE=",
    avatar_url: "https://avatars.githubusercontent.com/u/8171561?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/alxrcs",
    html_url: "https://github.com/alxrcs",
    followers_url: "https://api.github.com/users/alxrcs/followers",
    following_url: "https://api.github.com/users/alxrcs/following{/other_user}",
    gists_url: "https://api.github.com/users/alxrcs/gists{/gist_id}",
    starred_url: "https://api.github.com/users/alxrcs/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/alxrcs/subscriptions",
    organizations_url: "https://api.github.com/users/alxrcs/orgs",
    repos_url: "https://api.github.com/users/alxrcs/repos",
    events_url: "https://api.github.com/users/alxrcs/events{/privacy}",
    received_events_url: "https://api.github.com/users/alxrcs/received_events",
    type: "User",
    site_admin: false,
  },
];
